version: '3.0'
services:

   slave:
     user: "${USERID}:${GROUPID}"
     image: hashicorp/packer:light
     volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - "${JENKINS_HOME}:${JENKINS_HOME}:rw"
      - "${WORKSPACE}:${WORKSPACE}:rw"
     environment:
      REGION: $REGION
      AMI_NAME: $AMI_NAME
      DESCRIPTION: $DESCRIPTION
